In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [3]:
digits= load_digits()

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [14]:
lr=LogisticRegression()
lr.fit(X_train, Y_train)

C:\Users\HPENG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
lr.score(X_test, Y_test)

0.9648148148148148

In [16]:
svm=SVC()
svm.fit(X_train, Y_train)


SVC()

In [17]:
svm.score(X_test, Y_test)

0.9833333333333333

In [18]:
rf=RandomForestClassifier()
rf.fit(X_train, Y_train)

RandomForestClassifier()

In [19]:
rf.score(X_test, Y_test)

0.9666666666666667

In [20]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def get_score(model, X_train, X_test, Y_train, Y_test):
    model.fit(X_train, Y_train)
    return model.score(X_test,Y_test)

In [24]:
get_score(LogisticRegression(),X_train, X_test, Y_train, Y_test)

C:\Users\HPENG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [25]:
get_score(SVC(),X_train, X_test, Y_train, Y_test)

0.9833333333333333

In [26]:
get_score(RandomForestClassifier(),X_train, X_test, Y_train, Y_test)

0.975925925925926

In [27]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [34]:
scores_l =[]
scores_svm =[]
scores_rf =[]

for train_index,test_index in kf.split(digits.data):
    X_train, X_test, Y_train, Y_test= digits.data[train_index], digits.data[test_index],\
                                      digits.target[train_index], digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(),X_train, X_test, Y_train, Y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, Y_train, Y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train, X_test, Y_train, Y_test))
    # print(get_score(LogisticRegression(),X_train, X_test, Y_train, Y_test))
    # print(get_score(SVC(),X_train, X_test, Y_train, Y_test))
    # print(get_score(RandomForestClassifier(),X_train, X_test, Y_train, Y_test)

C:\Users\HPENG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HPENG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [35]:
 scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [36]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [37]:
scores_rf

[0.9282136894824707, 0.9565943238731218, 0.9181969949916527]

In [38]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\HPENG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HPENG\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])